project_id = "gzdxhuoqbfueciclrvxo"

[functions.analyze-pitch]
verify_jwt = false

[functions.analyze-pivots]
verify_jwt = false

[functions.mentor-chat]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false